services:
  visualdynamics:
    image: labioquim/visualdynamics:dev
    build:
      context: .
      dockerfile: apps/visualdynamics/Dockerfile.dev
    restart: always
    command: ["yarn", "workspace", "visualdynamics", "start:dev"]
    env_file: .env
    depends_on:
      - mailer
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - visualdynamics:/files
      - /app/node_modules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    restart: always
    image: labioquim/website:dev
    command: ["yarn", "workspace", "web", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - mailer
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/web/.next

  email:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    restart: always
    image: labioquim/email:dev
    command: ["yarn", "workspace", "web", "email"]
    ports:
      - "3003:3000"
    depends_on:
      - mailer
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/web/.next

  mailer:
    image: murilofuza/simple-mail:0.0.9
    restart: always
    env_file: .env
    ports:
      - "3002:3000"
    depends_on: 
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

volumes:
  redis:
    driver: nfsvol
  visualdynamics:
    driver: nfsvol