services:
  mailer:
    image: murilofuza/simple-mail:0.0.9
    restart: always
    env_file: .env
    networks:
      - traefik
    depends_on: 
      - redis

  redis:
    image: redis:alpine
    restart: always
    networks:
      - traefik
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file: .env
    restart: always
    networks:
      - traefik
    image: labioquim/website:latest
    ports:
      - 3000:3000
    depends_on:
      - mailer

  visualdynamics:
    build:
      context: .
      dockerfile: apps/visualdynamics/Dockerfile
    env_file: .env
    restart: always
    networks:
      - traefik
    image: labioquim/visualdynamics:latest
    ports:
      - 3001:3000
    depends_on:
      - mailer
      - redis

volumes:
  database:
    driver: nfsvol
  redis:
    driver: nfsvol

networks:
  traefik:
    external: true
  default: