services:
  mailer:
    image: murilofuza/simple-mail:0.0.9
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailer.rule=Host(`visualdynamics.fiocruz.br`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.mailer.service=mailer"
      - "traefik.http.services.mailer.loadbalancer.server.port=3000"
      - "traefik.http.routers.mailer.tls=true"
      - "traefik.http.routers.mailer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mailer.tls.domains[0].main=visualdynamics.fiocruz.br"
      - "traefik.http.routers.mailer.entryPoints=websecure"
    restart: always
    env_file: .env
    networks:
      - traefik
    depends_on: 
      - redis

  redis:
    image: redis:alpine
    restart: always
    networks:
      - traefik
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`visualdynamics.fiocruz.br`)"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.routers.web.tls.domains[0].main=visualdynamics.fiocruz.br"
      - "traefik.http.routers.web.entryPoints=websecure"
    env_file: .env
    restart: always
    networks:
      - traefik
    image: labioquim/website:latest
    depends_on:
      - mailer

  visualdynamics:
    build:
      context: .
      dockerfile: apps/visualdynamics/Dockerfile
    env_file: .env
    restart: always
    networks:
      - traefik
    image: labioquim/visualdynamics:latest
    depends_on:
      - mailer
      - redis

  proxy:
    restart: always
    image: traefik
    command:
      # - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedByDefault=false"

      - "--certificatesresolvers.letsencrypt.acme.email=labioquim@fiocruz.br"  # replace with your email
      - "--certificatesresolvers.letsencrypt.acme.storage=acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0"

      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_acme:/acme
      - traefik_logs:/logs
    ports:
      - "80:80"
      - "443:443"

volumes:
  database:
    driver: nfsvol
  redis:
    driver: nfsvol
  traefik_acme:
    driver: nfsvol
  traefik_logs:
    driver: nfsvol

networks:
  traefik:
    external: true
  default: